# This is a basic workflow to help you get started with Actions

name: Trigger publishing on my github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build job.
  trigger:
    # Get secret for the trigger.
    environment: trigger-publish-pages
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: send triggering event to my github pages
        id: trigger
        run: >-
          gh api --method POST -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          /repos/wenxin-wang/wenxin-wang.github.io/dispatches
          -f 'event_type=trigger-publish'
        env:
          GH_TOKEN: ${{ secrets.PAGES_GITHUB_TOKEN }}
